// "use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";
import { useRouter,usePathname } from "next/navigation";
import InputPageHeader from "@/components/common/inputPageHeader";
import { metadata } from "@/assets/metadata";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={inter.className}>
        {console.log("path....",pathname)}
        {pathname === "/healthInput" ? <InputPageHeader/> : <Header />}
        {children}
      </body>
    </html>
  );
}
